#!/bin/bash

# dumptruck
# Written by CLonsdale
# The dumptruck takes an asm file and dumps the opcodes into a hex escaped string for use in python

# The asm file needs to have the format specification in the top of the file
# BITS [16, 32, 64]

if [ $# -eq 1 ]
then
	nasm $1 -o dumptruck.shellcode # assemble
	# Get bytes, trim and escape
	xxd -p dumptruck.shellcode | tr -d '\n' | sed 's/\([a-f0-9]\{2\}\)/\\x\1/g'

	# sed explanation
	# get 2 characters that match this patter [a-f0-9]. Capture it and store it in \1
	# Replace it by the characters \\x\1. So b1 becomes \xb1

	rm dumptruck.shellcode
else
    echo "Usage: ./dumptruck <file.asm>"
fi
